from pathlib import Path
root=Path('/mnt/data/boostr_v028_patch')
logo='/assets/logos/boostr-logo-nav.png'

def shell(title, active, body, compact=False):
    if compact:
        nav=[('Home','/home','/'),('Ecosystem','/ecosystem','map'),('Manager OS','/manager','ops'),('Client OS','/app','app'),('Partner OS','/partner-dashboard','partner'),('Login','/login','auth'),('Audit','/audit','lead'),('82 Store','/82store','store'),('Portfolio','/portfolio','work')]
        navhtml=''.join(f'<a class="{active==href.strip("/") or (href=="/home" and active=="home") and "active" or ""}" href="{href}">{label}<span>{tag}</span></a>' for label,href,tag in nav)
        return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><link rel="icon" href="/assets/icons/09.-b-star-favicon.png"><link rel="stylesheet" href="/assets/boostr-mother/mother.css"></head><body><div class="ambient"></div><div class="compact-shell"><aside class="compact-side"><a class="brand" href="/home"><img src="{logo}" alt="BOOSTR Labs"><span><strong>BOOSTR Labs</strong><small>Mother UI v0.2.8</small></span></a><nav class="side-nav">{navhtml}</nav><div class="card glass"><b>Rule</b><p class="micro">BOOSTR UI is the system layer. Custom client pages stay custom.</p></div></aside><main class="compact-main">{body}<footer class="footer">BOOSTR Labs • Front-end ready for Codex backend</footer></main></div>{mobile_tabs(active)}</body></html>'''
    side='''<aside class="sidebar glass" aria-label="BOOSTR OS navigation"><a class="logo-mark" href="/home"><img src="/assets/logos/boostr-logo-nav.png" alt="BOOSTR Labs" onerror="this.replaceWith(Object.assign(document.createElement('span'),{className:'logo-letter',textContent:'B'}))"></a><nav class="icon-nav"><a CLASS_MANAGER href="/manager" title="Manager">⌘</a><a CLASS_APP href="/app" title="Client">◫</a><a CLASS_PARTNER href="/partner-dashboard" title="Partner">◇</a><a CLASS_AUDIT href="/audit" title="Audit">↯</a><a CLASS_PORTFOLIO href="/portfolio" title="Portfolio">◌</a></nav><div class="utility"><a CLASS_LOGIN href="/login" title="Role Login">◎</a><a CLASS_ECO href="/ecosystem" title="Ecosystem Map">?</a></div></aside>'''
    for key, val in [('CLASS_MANAGER','manager'),('CLASS_APP','app'),('CLASS_PARTNER','partner-dashboard'),('CLASS_AUDIT','audit'),('CLASS_PORTFOLIO','portfolio'),('CLASS_LOGIN','login'),('CLASS_ECO','ecosystem')]:
        side=side.replace(key, 'class="active"' if active==val else '')
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><meta name="description" content="BOOSTR Labs Custom Operating Systems."><link rel="icon" href="/assets/icons/09.-b-star-favicon.png"><link rel="stylesheet" href="/assets/boostr-mother/mother.css"></head><body><div class="ambient"></div><div class="os">{side}<main class="main">{topbar(active)}{body}<nav class="bottom-tabs glass" aria-label="BOOSTR OS quick switcher"><a class="{'active' if active=='manager' else ''}" href="/manager">Manager</a><a class="{'active' if active=='partner-dashboard' else ''}" href="/partner-dashboard">Partner</a><a class="{'active' if active=='app' else ''}" href="/app">Client</a><a href="/audit">Audit</a><a class="{'active' if active=='portfolio' else ''}" href="/portfolio">Portfolio</a><a class="plus" href="/login">+</a></nav><footer class="footer">BOOSTR Labs • Mother UI • Backend/auth/data pending Codex</footer></main></div>{mobile_tabs(active)}</body></html>'''

def mobile_tabs(active):
    return f'''<nav class="mobile-tabs"><a class="{'active' if active=='manager' else ''}" href="/manager">Manager</a><a class="{'active' if active=='app' else ''}" href="/app">Client</a><a class="{'active' if active=='partner-dashboard' else ''}" href="/partner-dashboard">Partner</a><a href="/audit">Audit</a><a class="{'active' if active=='login' else ''}" href="/login">Login</a></nav>'''

def topbar(active):
    labels={'home':'BOOSTR Labs','manager':'Manager OS','app':'Client OS','partner-dashboard':'Partner OS','admin':'Admin OS','ecosystem':'Ecosystem Map','modules':'Module Registry','portfolio':'Portfolio','login':'Role Access'}
    return f'''<header class="topbar glass"><div class="greeting"><span>{labels.get(active,'BOOSTR Labs')}</span><strong>{labels.get(active,'BOOSTR Labs')}</strong></div><div class="search">⌕ Search modules, leads, partners, stores...</div><a class="bell" href="/admin" title="Admin">♟</a><a class="role-pill" href="/login"><div class="avatar"></div><div><b>Role Access</b><div class="micro">Manager / Partner / Client</div></div></a></header>'''

home_body='''<section class="dashboard"><div class="left-col">
<section class="card glass"><div class="hero-grid"><div class="hero-copy"><div class="chip gold">Custom Operating Systems</div><h1>The system layer behind modern businesses.</h1><p>BOOSTR Labs builds websites, apps, dashboards, stores, audit funnels and operating systems around how each business actually works.</p><div class="actions"><a class="btn primary" href="/audit">Start BOOSTR Audit</a><a class="btn" href="/portfolio">View work</a><a class="btn" href="/login">Role access</a></div></div><div class="visual-card"><div class="orbital"><img src="/assets/logos/boostr-logo-nav.png" alt="BOOSTR"><span class="orbit-node o1">Website</span><span class="orbit-node o2">CRM</span><span class="orbit-node o3">Store</span><span class="orbit-node o4">Dashboard</span><span class="orbit-node o5">AI</span></div></div></div></section>
<section class="card glass"><div class="section-head"><div><h2>What we build</h2><div class="micro">Services stay clear. The system can grow later.</div></div><a class="chip" href="/modules">Registry</a></div><div class="metrics"><a class="metric" href="/audit"><span>Lead funnel</span><b>Audit</b><small>Live</small></a><a class="metric" href="/82store"><span>Commerce</span><b>Store</b><small>Live</small></a><a class="metric" href="/app"><span>Workspace</span><b>Client</b><small>Ready</small></a><a class="metric" href="/manager"><span>Operations</span><b>Manager</b><small>Ready</small></a></div></section>
<section class="card glass"><div class="section-head"><div><h2>Live network</h2><div class="micro">No ambassador or pulse layers. Audit is the main lead entry.</div></div></div><div class="network-grid"><div class="module"><b>BOOSTR Audit</b><p class="micro">Qualification and diagnosis.</p><a href="/audit">Open →</a></div><div class="module"><b>82 Store</b><p class="micro">Commerce frontend.</p><a href="/82store">Open →</a></div><div class="module"><b>82NGEL Link</b><p class="micro">Artist smart link.</p><a href="/82ngel">Open →</a></div><div class="module"><b>Janko Diorr</b><p class="micro">WESTDETRO smart link.</p><a href="/jankodiorr">Open →</a></div><div class="module"><b>GEMESE OS</b><p class="micro">Dashboard demo.</p><a href="/app/gemese">Open →</a></div><div class="module"><b>OMG Beauty</b><p class="micro">Portfolio route.</p><a href="/omgbeauty">Open →</a></div></div></section>
</div><div class="right-col"><section class="card glass"><div class="pulse"><span class="chip live">Ready for leads</span><strong>Audit</strong><div class="micro">Use /audit as the public entry point. Manager OS receives the backend wiring later.</div></div></section><section class="mini-switches"><a class="switch-card on glass" href="/login"><div class="switch-top"><b>Role Login</b><span class="toggle"></span></div><p class="micro">Manager, Partner, Client and Artist access shells.</p></a><a class="switch-card off glass" href="/admin"><div class="switch-top"><b>Backend</b><span class="toggle"></span></div><p class="micro">Codex connects auth, DB, payments and CRM next.</p></a></section><section class="card glass"><h3>Next backend move</h3><div class="timeline"><a class="task" href="/login"><span class="dot blue"></span><div><b>Auth by role</b><span>Manager / Partner / Client.</span></div><span>01</span></a><a class="task" href="/audit"><span class="dot"></span><div><b>Save audit leads</b><span>Cloudflare Function + D1.</span></div><span>02</span></a><a class="task" href="/manager"><span class="dot gold"></span><div><b>Manager inbox</b><span>See leads and modules.</span></div><span>03</span></a></div></section></div></section>'''

login_body='''<section class="card glass"><div class="section-head"><div><span class="eyebrow">Role Access</span><h1>Select workspace.</h1><p class="micro">Auth is pending. These routes define the backend contract for Codex.</p></div><a class="btn primary" href="/audit">Guest Audit</a></div><div class="login-grid"><a class="module role-card" href="/manager"><span class="chip gold">Manager</span><b>BOOSTR Manager</b><p class="micro">Leads, modules, builds, clients and operations.</p><span class="route">/manager</span></a><a class="module role-card" href="/partner-dashboard"><span class="chip">Partner</span><b>Partner OS</b><p class="micro">Referral paths, partner links and relationship tracking.</p><span class="route">/partner-dashboard</span></a><a class="module role-card" href="/app"><span class="chip">Client</span><b>Client OS</b><p class="micro">Projects, files, dashboards, stores and invoices.</p><span class="route">/app</span></a><a class="module role-card" href="/app/82ngel"><span class="chip live">Artist</span><b>Artist OS</b><p class="micro">Creator dashboard examples and smart link modules.</p><span class="route">/app/82ngel</span></a></div></section>'''

manager_body='''<section class="dashboard"><div class="left-col"><section class="card glass"><div class="section-head"><div><span class="eyebrow">BOOSTR Manager OS</span><h1>Operate the network.</h1><p class="micro">Frontend shell for leads, builds, clients, modules and partner flow.</p></div><a class="btn primary" href="/audit">Open Audit</a></div><div class="metrics"><a class="metric" href="/audit"><span>New entry</span><b>Audit</b><small>Guest lead</small></a><a class="metric" href="/app"><span>Clients</span><b>OS</b><small>Workspace</small></a><a class="metric" href="/partner-dashboard"><span>Partners</span><b>Links</b><small>Routes</small></a><a class="metric" href="/admin"><span>Backend</span><b>Next</b><small>Codex</small></a></div></section><section class="card glass"><h2>Manager flow</h2><div class="flow"><a class="flow-row" href="/audit"><b>Audit submitted</b><span>Lead enters as guest.</span><span class="chip live">Entry</span></a><a class="flow-row" href="/manager"><b>Manager review</b><span>BOOSTR chooses module path.</span><span class="chip">Review</span></a><a class="flow-row" href="/app"><b>Client workspace</b><span>Build becomes visible inside Client OS.</span><span class="chip">Workspace</span></a></div></section></div><div class="right-col"><section class="card glass"><h3>Modules to manage</h3><div class="timeline"><a class="task" href="/82store"><span class="dot gold"></span><div><b>82 Store</b><span>Commerce frontend.</span></div><span>Live</span></a><a class="task" href="/app/gemese"><span class="dot blue"></span><div><b>GEMESE OS</b><span>Partner dashboard.</span></div><span>Live</span></a><a class="task" href="/omgbeauty"><span class="dot"></span><div><b>OMG Beauty</b><span>Portfolio route.</span></div><span>Live</span></a></div></section></div></section>'''

app_body='''<section class="card glass"><div class="section-head"><div><span class="eyebrow">Client OS</span><h1>Client workspaces.</h1><p class="micro">Account-required shell. Backend will connect users, files, projects, orders and invoices.</p></div><a class="btn primary" href="/login">Role Access</a></div><div class="network-grid"><div class="module"><b>82NGEL OS</b><p class="micro">Artist dashboard demo.</p><a href="/app/82ngel">Open →</a></div><div class="module"><b>GEMESE OS</b><p class="micro">Partner/artist dashboard.</p><a href="/app/gemese">Open →</a></div><div class="module"><b>82 Store</b><p class="micro">Public store frontend.</p><a href="/82store">Open →</a></div><div class="module"><b>Audit History</b><p class="micro">Backend later.</p><a href="/audit">Start audit →</a></div><div class="module"><b>Files</b><p class="micro">Pending storage.</p><a href="/admin">Backend next →</a></div><div class="module"><b>Invoices</b><p class="micro">Pending payments.</p><a href="/admin">Backend next →</a></div></div></section>'''

admin_body='''<section class="card glass"><div class="section-head"><div><span class="eyebrow">Admin OS</span><h1>Backend control shell.</h1><p class="micro">This page is ready for Codex to connect auth, D1, CRM, payments and role permissions.</p></div><a class="btn primary" href="/manager">Manager OS</a></div><div class="metrics"><a class="metric" href="/login"><span>Auth</span><b>Roles</b><small>Pending</small></a><a class="metric" href="/audit"><span>Lead source</span><b>Audit</b><small>Ready</small></a><a class="metric" href="/82store"><span>Commerce</span><b>Orders</b><small>Pending</small></a><a class="metric" href="/partner-dashboard"><span>Partner</span><b>Refs</b><small>Pending</small></a></div></section>'''

partner_dash='''<section class="card glass"><div class="section-head"><div><span class="eyebrow">Partner OS</span><h1>Partner network.</h1><p class="micro">No ambassador layer. Partners are routes, referrals, intros and dashboards.</p></div><a class="btn primary" href="/audit">Send lead to Audit</a></div><div class="network-grid"><div class="module"><b>GEMESE Partner</b><p class="micro">Public partner route.</p><a href="/partner/gemese">Open →</a></div><div class="module"><b>Janko Partner</b><p class="micro">Creative partner route.</p><a href="/partner/janko">Open →</a></div><div class="module"><b>OMG Beauty</b><p class="micro">Portfolio/client route.</p><a href="/partner/omgbeauty">Open →</a></div><div class="module"><b>GEMESE OS</b><p class="micro">Dashboard demo.</p><a href="/app/gemese">Open →</a></div><div class="module"><b>Portfolio</b><p class="micro">Proof routes.</p><a href="/portfolio">Open →</a></div><div class="module"><b>Audit</b><p class="micro">Main intake path.</p><a href="/audit">Open →</a></div></div></section>'''

ecosystem_body='''<section class="card glass"><span class="eyebrow">Ecosystem Map</span><h1>One system layer. Custom worlds around it.</h1><p class="micro">BOOSTR UI handles system routes. Custom UI remains for client-specific pages, stores, artists and dashboards.</p><div class="actions"><a class="btn primary" href="/login">Role Access</a><a class="btn" href="/modules">Module Registry</a></div></section><section class="grid" style="margin-top:14px"><a class="card span4" href="/manager"><span class="chip gold">System</span><h3>Manager OS</h3><p class="micro">Internal operations.</p></a><a class="card span4" href="/app"><span class="chip gold">System</span><h3>Client OS</h3><p class="micro">Client workspaces.</p></a><a class="card span4" href="/partner-dashboard"><span class="chip gold">System</span><h3>Partner OS</h3><p class="micro">Partner network.</p></a><a class="card span4" href="/audit"><span class="chip live">Entry</span><h3>Audit</h3><p class="micro">Guest lead capture.</p></a><a class="card span4" href="/82store"><span class="chip">Custom</span><h3>82 Store</h3><p class="micro">Client commerce UI.</p></a><a class="card span4" href="/jankodiorr"><span class="chip">Custom</span><h3>Smart Links</h3><p class="micro">Artist/client worlds.</p></a></section>'''

modules_body='''<section class="card glass"><div class="section-head"><div><span class="eyebrow">Module Registry</span><h1>All active front-end routes.</h1><p class="micro">QA index. Every card should open a real route.</p></div><a class="btn primary" href="/audit">Start Audit</a></div><div class="network-grid">''' + ''.join([f'<div class="module"><b>{name}</b><p class="micro">{desc}</p><a href="{href}">{href} →</a></div>' for name,href,desc in [('Home','/home','Mother UI'),('Login','/login','Role access'),('Manager','/manager','Ops shell'),('Client OS','/app','Workspaces'),('Partner OS','/partner-dashboard','Partner hub'),('Admin','/admin','Backend shell'),('Audit','/audit','Lead capture'),('82 Store','/82store','Store frontend'),('82NGEL','/82ngel','Smart link'),('Janko','/jankodiorr','Smart link'),('GEMESE','/app/gemese','Dashboard'),('Portfolio','/portfolio','Proof index')]]) + '</div></section>'

portfolio_body='''<section class="card glass"><div class="section-head"><div><span class="eyebrow">Portfolio</span><h1>Proof inside the network.</h1><p class="micro">Selected systems and custom UI routes powered by BOOSTR Labs.</p></div><a class="btn primary" href="/audit">Start Audit</a></div><div class="network-grid"><div class="module"><b>OMG Beauty</b><p class="micro">Beauty landing / portfolio route.</p><a href="/omgbeauty">Open →</a></div><div class="module"><b>82 Store</b><p class="micro">Storefront and drop flow.</p><a href="/82store">Open →</a></div><div class="module"><b>82NGEL</b><p class="micro">Artist smart link.</p><a href="/82ngel">Open →</a></div><div class="module"><b>Janko Diorr</b><p class="micro">WESTDETRO smart link.</p><a href="/jankodiorr">Open →</a></div><div class="module"><b>GEMESE Dashboard</b><p class="micro">Partner dashboard demo.</p><a href="/app/gemese">Open →</a></div><div class="module"><b>SOLVE Automotive</b><p class="micro">External domain. Powered-by layer later.</p><a href="https://solveautomotive.com">Open external →</a></div></div></section>'''

partner_index='''<section class="card glass"><div class="section-head"><div><span class="eyebrow">Partner Routes</span><h1>Partner entry points.</h1><p class="micro">Partner pages do not need long forms. Leads go through BOOSTR Audit.</p></div><a class="btn primary" href="/audit">Send to Audit</a></div><div class="network-grid"><div class="module"><b>GEMESE</b><p class="micro">Music/creative route.</p><a href="/partner/gemese">Open →</a></div><div class="module"><b>Janko Diorr</b><p class="micro">Creative partner route.</p><a href="/partner/janko">Open →</a></div><div class="module"><b>OMG Beauty</b><p class="micro">Beauty portfolio route.</p><a href="/partner/omgbeauty">Open →</a></div></div></section>'''

def partner_page(name, tag, links):
    link_html=''.join(f'<a class="btn" href="{href}">{label}</a>' for label,href in links)
    return f'''<section class="card glass"><span class="eyebrow">BOOSTR x {name}</span><h1>{name}</h1><p class="micro">Partner route inside BOOSTR. Public leads should start through Audit; dashboards and client workspaces require role access later.</p><div class="actions"><a class="btn primary" href="/audit?ref={tag}">Start Audit</a>{link_html}<a class="btn" href="/partner-dashboard">Partner OS</a></div></section>'''

pages=[('index.html',shell('BOOSTR Labs — Custom Operating Systems','home',home_body)),('public/home/index.html',shell('BOOSTR Labs — Home','home',home_body)),('public/login/index.html',shell('BOOSTR Login — Role Access','login',login_body)),('public/manager/index.html',shell('BOOSTR Manager OS','manager',manager_body)),('public/app/index.html',shell('BOOSTR Client OS','app',app_body)),('public/admin/index.html',shell('BOOSTR Admin OS','admin',admin_body)),('public/partner-dashboard/index.html',shell('BOOSTR Partner OS','partner-dashboard',partner_dash)),('public/ecosystem/index.html',shell('BOOSTR Ecosystem','ecosystem',ecosystem_body,True)),('public/modules/index.html',shell('BOOSTR Module Registry','modules',modules_body,True)),('public/portfolio/index.html',shell('BOOSTR Portfolio','portfolio',portfolio_body,True)),('public/partner/index.html',shell('BOOSTR Partners','partner-dashboard',partner_index,True)),('public/partner/gemese/index.html',shell('BOOSTR x GEMESE','partner-dashboard',partner_page('GEMESE','gemese',[('GEMESE OS','/app/gemese')]),True)),('public/partner/janko/index.html',shell('BOOSTR x Janko Diorr','partner-dashboard',partner_page('Janko Diorr','janko',[('Janko Link','/jankodiorr')]),True)),('public/partner/omgbeauty/index.html',shell('BOOSTR x OMG Beauty','partner-dashboard',partner_page('OMG Beauty','omgbeauty',[('OMG Beauty','/omgbeauty')]),True))]
for path, html in pages:
    p=root/path
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(html, encoding='utf-8')
