name = "boostrlabs"
pages_build_output_dir = "dist"

[vars]
VITE_SITE_URL = "https://boostrlabs.pages.dev"
VITE_CONTACT_EMAIL = "boostrlabs@gmail.com"

[[d1_databases]]
binding = "DB"
database_name = "boostr_labs_core"
database_id = "3998802e-1829-48b4-91dc-971ecfd4c23d"
preview_database_id = "3998802e-1829-48b4-91dc-971ecfd4c23d"

[[r2_buckets]]
binding = "BOOSTR_ASSETS"
bucket_name = "boostr-labs-assets-prod"
preview_bucket_name = "boostr-labs-assets-prod"

[env.production.vars]
VITE_SITE_URL = "https://boostrlabs.pages.dev"
VITE_CONTACT_EMAIL = "boostrlabs@gmail.com"

[[env.production.d1_databases]]
binding = "DB"
database_name = "boostr_labs_core"
database_id = "3998802e-1829-48b4-91dc-971ecfd4c23d"

[[env.production.r2_buckets]]
binding = "BOOSTR_ASSETS"
bucket_name = "boostr-labs-assets-prod"

[env.preview.vars]
VITE_SITE_URL = "https://boostrlabs.pages.dev"
VITE_CONTACT_EMAIL = "boostrlabs@gmail.com"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "boostr_labs_core"
database_id = "3998802e-1829-48b4-91dc-971ecfd4c23d"
preview_database_id = "3998802e-1829-48b4-91dc-971ecfd4c23d"

[[env.preview.r2_buckets]]
binding = "BOOSTR_ASSETS"
bucket_name = "boostr-labs-assets-prod"
preview_bucket_name = "boostr-labs-assets-prod"
