const enc=new TextEncoder();
const now=()=>new Date().toISOString();
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const err=(m,s=400)=>json({error:m},s);
const body=async r=>{try{return await r.json()}catch{return {}}};
const bytesToHex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha(s){return bytesToHex(await crypto.subtle.digest('SHA-256',enc.encode(s)))}
function cookies(req){return Object.fromEntries((req.headers.get('cookie')||'').split(';').map(x=>x.trim().split('=')).filter(x=>x.length===2))}
function parts(ctx){const x=ctx.params.path;return Array.isArray(x)?x:String(x||'').split('/').filter(Boolean)}
async function ensure(DB){
 await DB.prepare(`CREATE TABLE IF NOT EXISTS agent_credentials(user_id TEXT PRIMARY KEY,public_slug TEXT NOT NULL UNIQUE,photo_url TEXT,status TEXT NOT NULL DEFAULT 'ACTIVE',active_from TEXT NOT NULL,active_to TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`).run();
 await DB.prepare('CREATE INDEX IF NOT EXISTS idx_agent_credentials_slug ON agent_credentials(public_slug)').run();
 await DB.prepare(`CREATE TABLE IF NOT EXISTS agent_readiness(user_id TEXT PRIMARY KEY,whatsapp_ready INTEGER NOT NULL DEFAULT 0,instagram_ready INTEGER NOT NULL DEFAULT 0,tiktok_ready INTEGER NOT NULL DEFAULT 0,kit_ready INTEGER NOT NULL DEFAULT 0,pricing_ready INTEGER NOT NULL DEFAULT 0,scripts_ready INTEGER NOT NULL DEFAULT 0,roleplay_ready INTEGER NOT NULL DEFAULT 0,approved_for_pool INTEGER NOT NULL DEFAULT 0,reviewed_at TEXT,reviewed_by TEXT,updated_at TEXT NOT NULL)`).run();
 await DB.prepare(`CREATE TABLE IF NOT EXISTS discount_codes(id TEXT PRIMARY KEY,code TEXT NOT NULL UNIQUE,kind TEXT NOT NULL,value REAL NOT NULL,min_amount REAL NOT NULL DEFAULT 500,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`).run();
}
async function session(ctx){const raw=cookies(ctx.request).boostr_agent_session;if(!raw)return null;const h=await sha(raw);const row=await ctx.env.AGENT_DB.prepare('SELECT * FROM sessions WHERE token_hash=? AND expires_at>?').bind(h,now()).first();if(!row)return null;if(row.role==='ADMIN')return{id:'admin',name:'BOOSTR Admin',role:'ADMIN'};return await ctx.env.AGENT_DB.prepare('SELECT id,name,email,role,created_at FROM users WHERE id=?').bind(row.user_id).first()}
function slugFromUser(u){const base=String(u.name||'agent').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,28)||'agent';return `${base}-${String(u.id).replace(/^usr_/,'').slice(0,8)}`}
async function ensureCredential(DB,u){let c=await DB.prepare('SELECT * FROM agent_credentials WHERE user_id=?').bind(u.id).first();if(c)return c;const slug=slugFromUser(u),t=now();await DB.prepare("INSERT INTO agent_credentials(user_id,public_slug,status,active_from,created_at,updated_at) VALUES(?,?,'ACTIVE',?,?,?)").bind(u.id,slug,u.created_at||t,t,t).run();return await DB.prepare('SELECT * FROM agent_credentials WHERE user_id=?').bind(u.id).first()}
async function ensureReadiness(DB,userId){let r=await DB.prepare('SELECT * FROM agent_readiness WHERE user_id=?').bind(userId).first();if(r)return r;await DB.prepare('INSERT INTO agent_readiness(user_id,updated_at) VALUES(?,?)').bind(userId,now()).run();return await DB.prepare('SELECT * FROM agent_readiness WHERE user_id=?').bind(userId).first()}
async function readiness(DB,u){const c=await ensureCredential(DB,u),r=await ensureReadiness(DB,u.id);const checks={credential_active:c.status==='ACTIVE',photo_ready:!!String(c.photo_url||'').trim(),whatsapp_ready:!!r.whatsapp_ready,instagram_ready:!!r.instagram_ready,tiktok_ready:!!r.tiktok_ready,kit_ready:!!r.kit_ready,pricing_ready:!!r.pricing_ready,scripts_ready:!!r.scripts_ready,roleplay_ready:!!r.roleplay_ready};const ready=Object.values(checks).every(Boolean)&&!!r.approved_for_pool;return {...r,...checks,ready,public_slug:c.public_slug,photo_url:c.photo_url||''}}
async function publicRow(DB,slug){return await DB.prepare(`SELECT u.id,u.name,u.email,u.created_at,c.public_slug,c.photo_url,c.status,c.active_from,c.active_to,(SELECT country FROM applications a WHERE lower(a.email)=lower(u.email) ORDER BY a.created_at DESC LIMIT 1) country,(SELECT city FROM applications a WHERE lower(a.email)=lower(u.email) ORDER BY a.created_at DESC LIMIT 1) city,(SELECT instagram FROM applications a WHERE lower(a.email)=lower(u.email) ORDER BY a.created_at DESC LIMIT 1) instagram FROM agent_credentials c JOIN users u ON u.id=c.user_id WHERE c.public_slug=?`).bind(slug).first()}
export async function onRequest(ctx){const DB=ctx.env.AGENT_DB;if(!DB)return err('AGENT_DB missing',500);await ensure(DB);const p=parts(ctx),method=ctx.request.method.toUpperCase();try{
 if(method==='GET'&&p[0]==='verify'&&p[1]){const row=await publicRow(DB,p[1]);if(!row)return err('Agente no encontrado',404);return json({name:row.name,photo_url:row.photo_url||'',status:row.status,active_from:row.active_from,active_to:row.active_to||'',country:row.country||'',city:row.city||'',instagram:row.instagram||'',public_slug:row.public_slug,verified:true})}
 const u=await session(ctx);
 if(method==='GET'&&p.join('/')==='me'){if(!u||u.role!=='AGENT')return err('Unauthorized',401);const c=await ensureCredential(DB,u);return json(await publicRow(DB,c.public_slug))}
 if(method==='PUT'&&p.join('/')==='me'){if(!u||u.role!=='AGENT')return err('Unauthorized',401);const b=await body(ctx.request),url=String(b.photo_url||'').trim();if(url&&!/^https:\/\//i.test(url))return err('La foto debe usar una URL https');const c=await ensureCredential(DB,u);await DB.prepare('UPDATE agent_credentials SET photo_url=?,updated_at=? WHERE user_id=?').bind(url,now(),u.id).run();return json(await publicRow(DB,c.public_slug))}
 if(method==='GET'&&p.join('/')==='readiness/me'){if(!u||u.role!=='AGENT')return err('Unauthorized',401);return json(await readiness(DB,u))}
 if(method==='GET'&&p.join('/')==='admin/agents'){if(!u||u.role!=='ADMIN')return err('Unauthorized',401);const {results}=await DB.prepare("SELECT id,name,email,created_at FROM users WHERE role='AGENT' ORDER BY created_at DESC").all();const out=[];for(const a of results){const full=await DB.prepare('SELECT * FROM users WHERE id=?').bind(a.id).first();const c=await ensureCredential(DB,full),rd=await readiness(DB,full);out.push({...a,public_slug:c.public_slug,photo_url:c.photo_url,status:c.status,active_from:c.active_from,active_to:c.active_to,...rd})}return json(out)}
 if(method==='POST'&&p[0]==='admin'&&p[1]==='agents'&&p[2]&&p[3]==='status'){if(!u||u.role!=='ADMIN')return err('Unauthorized',401);const b=await body(ctx.request),status=b.status==='INACTIVE'?'INACTIVE':'ACTIVE';const target=await DB.prepare("SELECT * FROM users WHERE id=? AND role='AGENT'").bind(p[2]).first();if(!target)return err('Agente no encontrado',404);await ensureCredential(DB,target);await DB.prepare('UPDATE agent_credentials SET status=?,active_to=?,updated_at=? WHERE user_id=?').bind(status,status==='INACTIVE'?now():null,now(),target.id).run();return json({ok:true})}
 if(method==='POST'&&p[0]==='admin'&&p[1]==='agents'&&p[2]&&p[3]==='readiness'){if(!u||u.role!=='ADMIN')return err('Unauthorized',401);const target=await DB.prepare("SELECT * FROM users WHERE id=? AND role='AGENT'").bind(p[2]).first();if(!target)return err('Agente no encontrado',404);await ensureReadiness(DB,target.id);const b=await body(ctx.request),fields=['whatsapp_ready','instagram_ready','tiktok_ready','kit_ready','pricing_ready','scripts_ready','roleplay_ready','approved_for_pool'];const v=Object.fromEntries(fields.map(k=>[k,b[k]?1:0]));await DB.prepare(`UPDATE agent_readiness SET whatsapp_ready=?,instagram_ready=?,tiktok_ready=?,kit_ready=?,pricing_ready=?,scripts_ready=?,roleplay_ready=?,approved_for_pool=?,reviewed_at=?,reviewed_by='ADMIN',updated_at=? WHERE user_id=?`).bind(v.whatsapp_ready,v.instagram_ready,v.tiktok_ready,v.kit_ready,v.pricing_ready,v.scripts_ready,v.roleplay_ready,v.approved_for_pool,now(),now(),target.id).run();return json(await readiness(DB,target))}
 if(method==='GET'&&p.join('/')==='admin/discounts'){if(!u||u.role!=='ADMIN')return err('Unauthorized',401);const {results}=await DB.prepare('SELECT * FROM discount_codes ORDER BY created_at DESC').all();return json(results)}
 if(method==='POST'&&p.join('/')==='admin/discounts'){if(!u||u.role!=='ADMIN')return err('Unauthorized',401);const b=await body(ctx.request),code=String(b.code||'').trim().toUpperCase(),kind=b.kind==='FIXED'?'FIXED':'PERCENT',value=Number(b.value),minAmount=Math.max(500,Number(b.min_amount||500));if(!/^[A-Z0-9_-]{3,24}$/.test(code)||!Number.isFinite(value)||value<=0||(kind==='PERCENT'&&value>=100))return err('Revisa el código y el descuento');const t=now();await DB.prepare('INSERT INTO discount_codes(id,code,kind,value,min_amount,active,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?)').bind('disc_'+crypto.randomUUID(),code,kind,value,minAmount,t,t).run();return json({ok:true},201)}
 if(method==='POST'&&p[0]==='admin'&&p[1]==='discounts'&&p[2]&&p[3]==='toggle'){if(!u||u.role!=='ADMIN')return err('Unauthorized',401);const b=await body(ctx.request);await DB.prepare('UPDATE discount_codes SET active=?,updated_at=? WHERE id=?').bind(b.active?1:0,now(),p[2]).run();return json({ok:true})}
 return err('Not found',404)
}catch(e){console.error(e);return err('No se pudo completar la operación',500)}}
