const enc=new TextEncoder();
const now=()=>new Date().toISOString();
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const err=(m,s=400)=>json({error:m},s);
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha(s){return hex(await crypto.subtle.digest('SHA-256',enc.encode(s)))}
function cookies(req){return Object.fromEntries((req.headers.get('cookie')||'').split(';').map(x=>x.trim().split('=')).filter(x=>x.length===2))}
async function session(ctx){const raw=cookies(ctx.request).boostr_agent_session;if(!raw)return null;const h=await sha(raw),s=await ctx.env.AGENT_DB.prepare('SELECT * FROM sessions WHERE token_hash=? AND expires_at>?').bind(h,now()).first();if(!s)return null;if(s.role==='ADMIN')return{id:'admin',role:'ADMIN'};return ctx.env.AGENT_DB.prepare('SELECT id,role FROM users WHERE id=?').bind(s.user_id).first()}
async function ensure(DB){await DB.prepare(`CREATE TABLE IF NOT EXISTS agent_content(id TEXT PRIMARY KEY,title TEXT NOT NULL,caption TEXT NOT NULL DEFAULT '',image_data TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'sales',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`).run()}
export async function onRequest(ctx){const DB=ctx.env.AGENT_DB;if(!DB)return err('AGENT_DB missing',500);await ensure(DB);const u=await session(ctx);if(!u)return err('Unauthorized',401);const method=ctx.request.method.toUpperCase();if(method==='GET'){const {results}=await DB.prepare('SELECT id,title,caption,image_data,category,created_at FROM agent_content WHERE active=1 ORDER BY created_at DESC').all();return json(results)}if(method==='POST'){if(u.role!=='ADMIN')return err('Unauthorized',401);let b={};try{b=await ctx.request.json()}catch{return err('Formato inválido')};const title=String(b.title||'').trim(),caption=String(b.caption||'').trim(),image=String(b.image_data||''),category=String(b.category||'sales').trim().slice(0,40)||'sales';if(!title||!image)return err('Falta título o imagen');if(!(image.startsWith('data:image/webp;base64,')||image.startsWith('data:image/jpeg;base64,')||image.startsWith('data:image/png;base64,')))return err('Formato de imagen no permitido');if(image.length>1400000)return err('La imagen es demasiado grande');const t=now(),id='content_'+crypto.randomUUID();await DB.prepare('INSERT INTO agent_content(id,title,caption,image_data,category,active,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?)').bind(id,title,caption,image,category,t,t).run();return json({ok:true,id},201)}if(method==='DELETE'){if(u.role!=='ADMIN')return err('Unauthorized',401);const id=new URL(ctx.request.url).searchParams.get('id');if(!id)return err('Falta id');await DB.prepare('UPDATE agent_content SET active=0,updated_at=? WHERE id=?').bind(now(),id).run();return json({ok:true})}return err('Method not allowed',405)}