const enc=new TextEncoder();
const now=()=>new Date().toISOString();
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const err=(m,s=400)=>json({error:m},s);
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha(s){return hex(await crypto.subtle.digest('SHA-256',enc.encode(s)))}
function cookies(req){return Object.fromEntries((req.headers.get('cookie')||'').split(';').map(x=>x.trim().split('=')).filter(x=>x.length===2))}
async function agent(ctx){const raw=cookies(ctx.request).boostr_agent_session;if(!raw)return null;const h=await sha(raw),s=await ctx.env.AGENT_DB.prepare('SELECT * FROM sessions WHERE token_hash=? AND expires_at>?').bind(h,now()).first();if(!s||s.role!=='AGENT')return null;return ctx.env.AGENT_DB.prepare("SELECT id,name,email,created_at FROM users WHERE id=? AND role='AGENT'").bind(s.user_id).first()}
function slug(u){const base=String(u.name||'agent').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,28)||'agent';return `${base}-${String(u.id).replace(/^usr_/,'').slice(0,8)}`}
async function ensureCredential(DB,u){await DB.prepare(`CREATE TABLE IF NOT EXISTS agent_credentials(user_id TEXT PRIMARY KEY,public_slug TEXT NOT NULL UNIQUE,photo_url TEXT,status TEXT NOT NULL DEFAULT 'ACTIVE',active_from TEXT NOT NULL,active_to TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`).run();let c=await DB.prepare('SELECT * FROM agent_credentials WHERE user_id=?').bind(u.id).first();if(c)return c;const t=now();await DB.prepare("INSERT INTO agent_credentials(user_id,public_slug,status,active_from,created_at,updated_at) VALUES(?,?,'ACTIVE',?,?,?)").bind(u.id,slug(u),u.created_at||t,t,t).run();return DB.prepare('SELECT * FROM agent_credentials WHERE user_id=?').bind(u.id).first()}
export async function onRequest(ctx){const DB=ctx.env.AGENT_DB;if(!DB)return err('AGENT_DB missing',500);const u=await agent(ctx);if(!u)return err('Unauthorized',401);const c=await ensureCredential(DB,u);if(ctx.request.method==='GET')return json({photo_url:c.photo_url||''});if(ctx.request.method!=='PUT')return err('Method not allowed',405);let b={};try{b=await ctx.request.json()}catch{return err('Formato inválido')};const photo=String(b.photo_url||'');if(photo&&!(photo.startsWith('data:image/webp;base64,')||photo.startsWith('data:image/jpeg;base64,')||photo.startsWith('data:image/png;base64,')))return err('Formato de imagen no permitido');if(photo.length>700000)return err('La foto es demasiado grande');await DB.prepare('UPDATE agent_credentials SET photo_url=?,updated_at=? WHERE user_id=?').bind(photo,now(),u.id).run();return json({ok:true,photo_url:photo})}